# E-Mail
spring.mail.host=localhost
spring.mail.port=1025

# Database
spring.datasource.url=jdbc:mariadb://localhost:3306/komunumo?serverTimezone=Europe/Berlin&allowMultiQueries=true
spring.datasource.username=komunumo
spring.datasource.password=komunumo

# Application specific configuration
komunumo.demo.enabled=true
komunumo.instance.admin=admin@example.com
